import { c as create_ssr_component, e as escape } from "./ssr.js";
const css$1 = {
  code: ".nav-logo.svelte-12x0e5s.svelte-12x0e5s{width:3.5rem}.nav-links.svelte-12x0e5s.svelte-12x0e5s{display:none}.nav.svelte-12x0e5s.svelte-12x0e5s{height:5rem;padding:1rem;display:grid;-webkit-box-align:center;align-items:center;-webkit-transition:var(--transition);transition:var(--transition)}.nav-center.svelte-12x0e5s.svelte-12x0e5s{width:100%;max-width:var(--max-width);margin:0 auto}.nav-header.svelte-12x0e5s.svelte-12x0e5s{display:grid;grid-template-columns:1fr 1fr;-webkit-box-align:center;align-items:center}.nav-btn.svelte-12x0e5s.svelte-12x0e5s{background:transparent;border-color:transparent;color:var(--clr-primary-5);font-size:2rem;cursor:pointer;justify-self:right}@media screen and (min-width: 800px){.nav-btn.svelte-12x0e5s.svelte-12x0e5s{display:none}.nav-links.svelte-12x0e5s.svelte-12x0e5s{display:grid;grid-template-columns:repeat(4, 1fr);justify-items:center;gap:2rem;justify-self:end}.nav-links.svelte-12x0e5s a.svelte-12x0e5s{text-transform:uppercase;color:var(--clr-grey-2);letter-spacing:var(--spacing);-webkit-transition:var(--transition);transition:var(--transition)}.nav-links.svelte-12x0e5s a.svelte-12x0e5s:hover{color:var(--clr-primary-5)}.nav-center.svelte-12x0e5s.svelte-12x0e5s{display:grid;grid-template-columns:auto 1fr;-webkit-box-align:center;align-items:center}}.navbar-fixed.svelte-12x0e5s.svelte-12x0e5s{position:fixed;top:0;left:0;width:100%;background-color:var(--clr-primary-9);z-index:2;box-shadow:var(--light-shadow)}.sidebar.svelte-12x0e5s.svelte-12x0e5s{position:fixed;top:0;left:0;width:100%;height:100%;background:var(--clr-primary-9);z-index:4;display:grid;place-items:center;-webkit-transition:var(--transition);transition:var(--transition);-webkit-transform:translateX(-100%);transform:translateX(-100%)}.show-sidebar.svelte-12x0e5s.svelte-12x0e5s{-webkit-transform:translateX(0);transform:translateX(0);transition:--var(transition)}.sidebar-links.svelte-12x0e5s.svelte-12x0e5s{text-align:center}.sidebar-links.svelte-12x0e5s a.svelte-12x0e5s{font-size:2rem;text-transform:uppercase;letter-spacing:var(--spacing);color:var(--clr-grey-5);transition:--var(transition);letter-spacing:--spacing;display:inline-block;margin-bottom:1.5rem}.sidebar-links.svelte-12x0e5s a.svelte-12x0e5s:hover{color:var(--clr-primary-5)}.social-icon.svelte-12x0e5s.svelte-12x0e5s{color:var(--clr-grey-5)}.social-icon.svelte-12x0e5s.svelte-12x0e5s:hover{color:var(--clr-primary-5)}.close-btn.svelte-12x0e5s.svelte-12x0e5s{position:absolute;top:1rem;right:1rem;font-size:3rem;background:transparent;border:transparent;-webkit-transition:var(--transition);transition:var(--transition);color:var(--red-dark)}.close-btn.svelte-12x0e5s.svelte-12x0e5s:hover{color:var(--clr-primary-5)}",
  map: null
};
const Navbar = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css$1);
  return `   <nav class="${["nav svelte-12x0e5s", ""].join(" ").trim()}" id="nav"><div class="nav-center svelte-12x0e5s"> <div class="nav-header svelte-12x0e5s"><img src="./images/logo.svg" alt="logo of website Curious data" class="nav-logo svelte-12x0e5s"> <button class="nav-btn svelte-12x0e5s" id="nav-btn" data-svelte-h="svelte-1544k26"><i class="fas fa-bars"></i></button></div>  <ul class="nav-links svelte-12x0e5s" data-svelte-h="svelte-1g4e7lu"><li><a href="/" class="svelte-12x0e5s">Home</a></li> <li><a href="/about" class="svelte-12x0e5s">About</a></li> <li><a href="/projects" class="svelte-12x0e5s">Projects</a></li>  <li><a href="/contact" class="svelte-12x0e5s">Contact</a></li></ul></div></nav>  <aside class="${["sidebar svelte-12x0e5s", ""].join(" ").trim()}" id="sidebar"><div><button class="close-btn svelte-12x0e5s" id="close-btn" data-svelte-h="svelte-1o2zbdg"><i class="fas fa-times"></i></button>  <ul class="sidebar-links svelte-12x0e5s"><li><a href="/" class="svelte-12x0e5s" data-svelte-h="svelte-4jdyte">home</a></li> <li><a href="/about" class="svelte-12x0e5s" data-svelte-h="svelte-arlthl">about</a></li> <li><a href="/projects" class="svelte-12x0e5s" data-svelte-h="svelte-1o2llyz">projects</a></li>  <li><a href="/contact" class="svelte-12x0e5s" data-svelte-h="svelte-1a0tcyr">contact</a></li></ul>  <ul class="social-icons" data-svelte-h="svelte-1jor3da"> <li><a href="https://www.linkedin.com/in/annesophiepereira/" target="_blank" class="social-icon svelte-12x0e5s"><i class="fab fa-linkedin"></i></a></li>    <li><a href="https://github.com/DameAnneSo" target="_blank" class="social-icon svelte-12x0e5s"><i class="fa-brands fa-github"></i></a></li>  <li><a href="https://bsky.app/profile/curiousdata.bsky.social" target="_blank" class="social-icon svelte-12x0e5s"><i class="fa-brands fa-bluesky"></i></a></li> </ul></div></aside> `;
});
const css = {
  code: ".footer.svelte-1whhmcy.svelte-1whhmcy{height:12rem;padding-bottom:2rem;background-color:var(--clr-primary-1);display:grid;place-items:center}.footer.svelte-1whhmcy .social-icons.svelte-1whhmcy{margin-bottom:2rem}.footer.svelte-1whhmcy .social-icon.svelte-1whhmcy{color:var(--clr-primary-5)}.footer.svelte-1whhmcy .social-icon.svelte-1whhmcy:hover{color:var(--clr-primary-7)}.footer.svelte-1whhmcy p.svelte-1whhmcy{font-size:1rem;text-transform:capitalize;color:var(--clr-primary-4)}",
  map: null
};
const Footer_classic = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  const date = (/* @__PURE__ */ new Date()).getFullYear();
  $$result.css.add(css);
  return ` <footer class="footer svelte-1whhmcy"><ul class="social-icons svelte-1whhmcy" data-svelte-h="svelte-mf25f8"> <li><a href="https://www.linkedin.com/in/annesophiepereira/" target="_blank" class="social-icon svelte-1whhmcy"><i class="fab fa-linkedin"></i></a></li>   <li><a href="https://github.com/DameAnneSo" target="_blank" class="social-icon svelte-1whhmcy"><i class="fa-brands fa-github"></i></a></li>  <li><a href="https://bsky.app/profile/curiousdata.bsky.social" target="_blank" class="social-icon svelte-1whhmcy"><i class="fa-brands fa-bluesky"></i></a></li> </ul> <p class="svelte-1whhmcy">© <span id="date">${escape(date)}</span> Anne-Sophie Pereira De Sá. All rights reserved</p> </footer>`;
});
export {
  Footer_classic as F,
  Navbar as N
};
