import { c as create_ssr_component } from "./ssr.js";
const css = {
  code: ".projects-text.svelte-1f1yoex.svelte-1f1yoex{width:85vw;max-width:60rem;margin:0 auto}.project.svelte-1f1yoex.svelte-1f1yoex{position:relative;background:var(--clr-primary-5);border-radius:var(--radius);margin-bottom:2rem}.project-info.svelte-1f1yoex.svelte-1f1yoex{text-align:center;color:var(--clr-white);position:absolute;top:50%;left:50%;-webkit-transform:translate(-50%, -50%);transform:translate(-50%, -50%);-webkit-transition:var(--transition);transition:var(--transition);opacity:0}.project-info.svelte-1f1yoex h4.svelte-1f1yoex{line-height:1.5rem}.project-info.svelte-1f1yoex p.svelte-1f1yoex{text-transform:capitalize;color:var(--clr-white);font-size:0.9rem}.project.svelte-1f1yoex:hover .project-info.svelte-1f1yoex{opacity:1}.project-img.svelte-1f1yoex.svelte-1f1yoex{-webkit-transition:var(--transition);transition:var(--transition);border-radius:var(--radius);height:18rem;-o-object-fit:cover;object-fit:cover}.project.svelte-1f1yoex:hover .project-img.svelte-1f1yoex{opacity:0.1}.project.svelte-1f1yoex.svelte-1f1yoex::after{content:'';position:absolute;top:0;left:0;width:100%;height:100%;border:0.25rem solid var(--clr-white);border-radius:var(--radius);-webkit-transition:var(--transition);transition:var(--transition);opacity:0}.project.svelte-1f1yoex.svelte-1f1yoex:hover::after{opacity:1;-webkit-transform:scale(0.8);transform:scale(0.8)}@media screen and (min-width: 676px){.projects-center.svelte-1f1yoex.svelte-1f1yoex{display:grid;grid-template-columns:1fr 1fr;-webkit-column-gap:2rem;-moz-column-gap:2rem;column-gap:2rem}}@media screen and (min-width: 676px){.projects-center.svelte-1f1yoex.svelte-1f1yoex{grid-template-rows:repeat(4, 300px);row-gap:2rem;grid-template-areas:'a b '\n        'c d '\n        'e f'\n        'g g'}.project-img.svelte-1f1yoex.svelte-1f1yoex{height:100%}.project.svelte-1f1yoex.svelte-1f1yoex{height:100%}.project-1.svelte-1f1yoex.svelte-1f1yoex{grid-area:a}.project-2.svelte-1f1yoex.svelte-1f1yoex{grid-area:b}.project-3.svelte-1f1yoex.svelte-1f1yoex{grid-area:c}.project-4.svelte-1f1yoex.svelte-1f1yoex{grid-area:d}.project-5.svelte-1f1yoex.svelte-1f1yoex{grid-area:e}.project-6.svelte-1f1yoex.svelte-1f1yoex{grid-area:f}.project-more.svelte-1f1yoex.svelte-1f1yoex{grid-area:g}}.projects-center.svelte-1f1yoex.svelte-1f1yoex{background-color:var(--clr-primary-9);padding:2rem;border-radius:var(--radius)}.project-more.svelte-1f1yoex.svelte-1f1yoex{background-color:var(--clr-primary-9)}",
  map: null
};
const Projects_gallery = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<section class="portfolio-page-center" data-svelte-h="svelte-cujg4w"> <div class="section-title"><h2>My work</h2> <div class="underline"></div>  <p class="projects-text svelte-1f1yoex"></p> <ul><li>&#39;Viz of Day&#39; on Tableau Public three times</li> <li>Longlisted for the &#39;Information is Beautiful Awards&#39; (IIAB) three times</li> <li>Top 10 in Tableau&#39;s Ironviz Competition for 2021</li></ul></div> <div class="section-center projects-center svelte-1f1yoex"> <a href="projects/buffy_viz" target="_blank" class="project-1 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_buffy_3.png" alt="screenshot of the dataviz 6 reasons to (re)watch Buffy the Vampire Slayer" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">6 reasons to (re)watch Buffy the Vampire Slayer</h4> <p class="svelte-1f1yoex">Tableau Ironviz Top 10 qualifiers (2021)
            <br>
            Long listed in the IIAB (2022)</p></div> <div class="project-IIBA-logo"><img src="./images/2022_IIBA_Longlist.png" alt="2022 IIBA Longlist" style="position: absolute; right: 0; bottom: 0; max-width: 25%; z-index: 1;"></div></article></a>   <a href="projects/tedlasso_viz" target="_blank" class="project-2 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_tedlasso.gif" alt="screenshot of the dataviz Ted Lasso and his pop culture references" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">Ted Lasso and his pop culture references</h4> <p class="svelte-1f1yoex">&#39;Viz of the Day&#39; on Tableau Public (2023)</p></div> <div class="project-IIBA-logo"><img src="./images/2023_IIBA_Longlist.png" alt="2022 IIBA Longlist" style="position: absolute; right: 0; bottom: 0; max-width: 25%; z-index: 1;"></div></article></a>   <a href="https://www.linkedin.com/business/marketing/blog/research-and-insights/be-part-of-the-sustainability-conversation-on-linkedin-and-not-just-on-earth-day" target="_blank" class="project-3 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_sustainability.png" alt="screenshot of the dataviz LinkedIn: sustainability conversations" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">LinkedIn: sustainability conversations</h4> <p class="svelte-1f1yoex">Posted on the LinkedIn Marketing blog</p></div></article></a>   <a href="projects/eurovisionjury_viz" target="_blank" class="project-4 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_eurovision_juries_2.png" alt="screenshot of the dataviz 'Eurovision: does jury bias lead to victory?'" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">Eurovision: does jury bias lead to victory?</h4> <p class="svelte-1f1yoex">&#39;Viz of the Day&#39; on Tableau Public (2021)
            <br>Long listed in the IIAB (2022)</p></div> <div class="project-IIBA-logo"><img src="./images/2022_IIBA_Longlist.png" alt="2022 IIBA Longlist" style="position: absolute; right: 0; bottom: 0; max-width: 25%; z-index: 1;"></div></article></a>   <a href="projects/depechemode_viz" target="_blank" class="project-5 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_depechemode.png" alt="screenshot of the dataviz 'Depeche Mode: an exploration of my devotion'" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">Depeche Mode: an exploration of my devotion</h4>  <p class="svelte-1f1yoex">&#39;Viz of the Day&#39; on Tableau Public (2022)</p></div></article></a>   <a href="projects/cat_viz" target="_blank" class="project-6 svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_cat.gif" alt="screenshot of the dataviz 'Things I love about my cat'" class="project-img svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">Things I love about my cat</h4>  <p class="svelte-1f1yoex"></p></div></article></a>   <a href="https://public.tableau.com/app/profile/anne.sophie5083" target="_blank" class="project-more svelte-1f1yoex"><article class="project svelte-1f1yoex"><img src="./images/portfolio_other_banner.png" alt="screenshot of the portfolio dataviz on Tableau public" class="project-img project-more svelte-1f1yoex"> <div class="project-info svelte-1f1yoex"><h4 class="svelte-1f1yoex">Want more?</h4> <p class="svelte-1f1yoex">More projects on my Tableau Public profile</p></div></article></a> </div> </section>`;
});
export {
  Projects_gallery as P
};
